/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class menu_caracteress extends javax.swing.JFrame {

    /**
     * Creates new form menu_caracteress
     */
    public menu_caracteress() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parra = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        sumar = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        quitarvocales = new javax.swing.JCheckBoxMenuItem();
        cambiarvocales = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE PARRAFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel2.setText("RESULTADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 184, -1, -1));
        getContentPane().add(parra, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 117, 272, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 181, 272, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 300));

        sumar.setText("OPERACIONES");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Sumar Numeros");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        sumar.add(jCheckBoxMenuItem1);

        quitarvocales.setSelected(true);
        quitarvocales.setText("Quitar Vocales");
        quitarvocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarvocalesActionPerformed(evt);
            }
        });
        sumar.add(quitarvocales);

        cambiarvocales.setSelected(true);
        cambiarvocales.setText("Cambiar Vocales");
        cambiarvocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarvocalesActionPerformed(evt);
            }
        });
        sumar.add(cambiarvocales);

        jMenuBar1.add(sumar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // SUMAR NUMEROS
        String parrafo;
        char caracter;
        int x,longi,num,total=0;
        parrafo = parra.getText();
        longi = parrafo.length();
        for(x=0;x<longi;x++){
        caracter = parrafo.charAt(x);
        if(caracter == '1' || caracter == '2' || caracter == '3' || caracter == '4' || caracter == '5' || caracter == '6' || caracter == '7' || caracter == '8' || caracter == '9'){
        num = Integer.parseInt(String.valueOf(caracter));
        total = total + num;
        }
        }
        resul.setText(String.valueOf(total));
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void quitarvocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarvocalesActionPerformed
        // QUITAR VOCALES
        String parrafo,newparra="";
        char caracter;
        int x,longi;
        parrafo = parra.getText();
        longi = parrafo.length();
        for(x=0;x<longi;x++){
        caracter = parrafo.charAt(x);
        if(caracter != 'a' && caracter != 'e' && caracter != 'i'  && caracter != 'o'  && caracter != 'u'){
        newparra = newparra + caracter;
        }
        }
        resul.setText(newparra);
    }//GEN-LAST:event_quitarvocalesActionPerformed

    private void cambiarvocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarvocalesActionPerformed
        // CAMBIAR VOCALES
        String parrafo,cambiar;
        parrafo=parra.getText();
        cambiar=parrafo.replace('a','1').replace('e', '2').replace('i', '3').replace('o', '4').replace('u', '5');
        resul.setText(cambiar);
    }//GEN-LAST:event_cambiarvocalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_caracteress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_caracteress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_caracteress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_caracteress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_caracteress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem cambiarvocales;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField parra;
    private javax.swing.JCheckBoxMenuItem quitarvocales;
    private javax.swing.JTextField resul;
    private javax.swing.JMenu sumar;
    // End of variables declaration//GEN-END:variables
}
