/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class ImpuestosMenu extends javax.swing.JFrame {

    /**
     * Creates new form ImpuestosMenu
     */
    public ImpuestosMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        sala = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        IVA = new javax.swing.JCheckBoxMenuItem();
        ISR = new javax.swing.JCheckBoxMenuItem();
        IGGS = new javax.swing.JCheckBoxMenuItem();
        ImEspecial = new javax.swing.JCheckBoxMenuItem();
        Todos = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 72, -1, -1));

        jLabel2.setText("SALARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 119, -1, -1));

        jLabel3.setText("SALARIO CON DESCUENTO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 164, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 69, 94, -1));
        getContentPane().add(sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 116, 94, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 161, 94, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 230));

        jMenu1.setText("DESCUENTOS");

        IVA.setSelected(true);
        IVA.setText("IVA");
        IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IVAActionPerformed(evt);
            }
        });
        jMenu1.add(IVA);

        ISR.setSelected(true);
        ISR.setText("ISR");
        ISR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISRActionPerformed(evt);
            }
        });
        jMenu1.add(ISR);

        IGGS.setSelected(true);
        IGGS.setText("IGSS");
        IGGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGGSActionPerformed(evt);
            }
        });
        jMenu1.add(IGGS);

        ImEspecial.setSelected(true);
        ImEspecial.setText("IMPUESTO ESPECIAL");
        ImEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImEspecialActionPerformed(evt);
            }
        });
        jMenu1.add(ImEspecial);

        Todos.setSelected(true);
        Todos.setText("TODOS");
        Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosActionPerformed(evt);
            }
        });
        jMenu1.add(Todos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IVAActionPerformed
        // IVA
        String valor;
        double salario,descuento,salario_desc;
        valor = sala.getText();
        salario = Double.parseDouble(valor);
        descuento = salario * 0.010;
        salario_desc = salario - descuento;
        resul.setText(String.valueOf(salario_desc));
    }//GEN-LAST:event_IVAActionPerformed

    private void ISRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISRActionPerformed
        //ISR
        
        String valor;
        double salario,descuento,salario_desc;
        valor = sala.getText();
        salario = Double.parseDouble(valor);
        descuento = salario * 0.042;
        salario_desc = salario - descuento;
        resul.setText(String.valueOf(salario_desc));
      
    }//GEN-LAST:event_ISRActionPerformed

    private void IGGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGGSActionPerformed
        // IGSS
         String valor;
        double salario,descuento,salario_desc;
        valor = sala.getText();
        salario = Double.parseDouble(valor);
        descuento = salario * 0.012;
        salario_desc = salario - descuento;
        resul.setText(String.valueOf(salario_desc));
    }//GEN-LAST:event_IGGSActionPerformed

    private void ImEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImEspecialActionPerformed
        // IMPUESTO ESPECIAL
        String valor;
        double salario,descuento,salario_desc;
        valor = sala.getText();
        salario = Double.parseDouble(valor);
        descuento = salario * 0.015;
        salario_desc = salario - descuento;
        resul.setText(String.valueOf(salario_desc));
    }//GEN-LAST:event_ImEspecialActionPerformed

    private void TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosActionPerformed
        // TODOS
        String valor;
        double salario,descuento,descuent1,descuent2,descuent3,salario_desc;
        valor=sala.getText();
        salario=Double.parseDouble(valor);
        descuento = salario * 0.010;
        descuent1 = salario * 0.042;
        descuent2 = salario * 0.012;
        descuent3 = salario * 0.015;
        salario_desc = salario-descuento-descuent1-descuent2-descuent3;
        
        resul.setText(String.valueOf(salario_desc));
           
            
        
    }//GEN-LAST:event_TodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpuestosMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpuestosMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpuestosMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpuestosMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpuestosMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem IGGS;
    private javax.swing.JCheckBoxMenuItem ISR;
    private javax.swing.JCheckBoxMenuItem IVA;
    private javax.swing.JCheckBoxMenuItem ImEspecial;
    private javax.swing.JCheckBoxMenuItem Todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField resul;
    private javax.swing.JTextField sala;
    // End of variables declaration//GEN-END:variables
}
