/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Formando_Palabras extends javax.swing.JFrame {

    /**
     * Creates new form Formando_Palabras
     */
    public Formando_Palabras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        botonE = new javax.swing.JButton();
        botonF = new javax.swing.JButton();
        botonG = new javax.swing.JButton();
        botonH = new javax.swing.JButton();
        botonI = new javax.swing.JButton();
        botonJ = new javax.swing.JButton();
        botonK = new javax.swing.JButton();
        botonL = new javax.swing.JButton();
        botonM = new javax.swing.JButton();
        botonN = new javax.swing.JButton();
        botonO = new javax.swing.JButton();
        botonP = new javax.swing.JButton();
        botonQ = new javax.swing.JButton();
        botonR = new javax.swing.JButton();
        botonS = new javax.swing.JButton();
        botonT = new javax.swing.JButton();
        botonU = new javax.swing.JButton();
        botonV = new javax.swing.JButton();
        botonW = new javax.swing.JButton();
        botonX = new javax.swing.JButton();
        botonY = new javax.swing.JButton();
        botonZ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        resul = new javax.swing.JTextField();
        jButton27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonA.setText("A");
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });
        getContentPane().add(botonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 36, -1, -1));

        botonB.setText("B");
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });
        getContentPane().add(botonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 36, -1, -1));

        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        getContentPane().add(botonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 36, -1, -1));

        botonD.setText("D");
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });
        getContentPane().add(botonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 36, -1, -1));

        botonE.setText("E");
        botonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEActionPerformed(evt);
            }
        });
        getContentPane().add(botonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 36, -1, -1));

        botonF.setText("F");
        botonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFActionPerformed(evt);
            }
        });
        getContentPane().add(botonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 36, -1, -1));

        botonG.setText("G");
        botonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGActionPerformed(evt);
            }
        });
        getContentPane().add(botonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 70, -1, -1));

        botonH.setText("H");
        botonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHActionPerformed(evt);
            }
        });
        getContentPane().add(botonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 70, -1, -1));

        botonI.setText("I");
        botonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIActionPerformed(evt);
            }
        });
        getContentPane().add(botonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 70, -1, -1));

        botonJ.setText("J");
        botonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJActionPerformed(evt);
            }
        });
        getContentPane().add(botonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 70, -1, -1));

        botonK.setText("K");
        botonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonKActionPerformed(evt);
            }
        });
        getContentPane().add(botonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 70, -1, -1));

        botonL.setText("L");
        botonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLActionPerformed(evt);
            }
        });
        getContentPane().add(botonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 70, -1, -1));

        botonM.setText("M");
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });
        getContentPane().add(botonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, -1));

        botonN.setText("N");
        botonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNActionPerformed(evt);
            }
        });
        getContentPane().add(botonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 104, -1, -1));

        botonO.setText("O");
        botonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOActionPerformed(evt);
            }
        });
        getContentPane().add(botonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 104, -1, -1));

        botonP.setText("P");
        botonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPActionPerformed(evt);
            }
        });
        getContentPane().add(botonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 104, -1, -1));

        botonQ.setText("Q");
        botonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQActionPerformed(evt);
            }
        });
        getContentPane().add(botonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 104, -1, -1));

        botonR.setText("R");
        botonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRActionPerformed(evt);
            }
        });
        getContentPane().add(botonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 104, -1, -1));

        botonS.setText("S");
        botonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSActionPerformed(evt);
            }
        });
        getContentPane().add(botonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 133, -1, -1));

        botonT.setText("T");
        botonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTActionPerformed(evt);
            }
        });
        getContentPane().add(botonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 133, -1, -1));

        botonU.setText("U");
        botonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUActionPerformed(evt);
            }
        });
        getContentPane().add(botonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 133, -1, -1));

        botonV.setText("V");
        botonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVActionPerformed(evt);
            }
        });
        getContentPane().add(botonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 133, -1, -1));

        botonW.setText("W");
        botonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonWActionPerformed(evt);
            }
        });
        getContentPane().add(botonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 133, -1, -1));

        botonX.setText("X");
        botonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXActionPerformed(evt);
            }
        });
        getContentPane().add(botonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 133, -1, -1));

        botonY.setText("Y");
        botonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYActionPerformed(evt);
            }
        });
        getContentPane().add(botonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 162, -1, -1));

        botonZ.setText("Z");
        botonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonZActionPerformed(evt);
            }
        });
        getContentPane().add(botonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 162, -1, -1));

        jLabel1.setText("RESULTADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 255, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resulActionPerformed(evt);
            }
        });
        jPanel1.add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 220, -1));

        jButton27.setText("LIMPIAR");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonKActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra11;
    letra11 = botonK.getText();
    caja = caja + letra11;
    resul.setText(caja);
    }//GEN-LAST:event_botonKActionPerformed

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra1;
    letra1 = botonA.getText();
    caja = caja + letra1;
    resul.setText(caja);
    }//GEN-LAST:event_botonAActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        resul.setText(null);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed
        // TODO add your handling code here:
                String caja;
    caja = resul.getText();
    String letra2;
    letra2 = botonB.getText();
    caja = caja + letra2;
    resul.setText(caja);
    }//GEN-LAST:event_botonBActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra3;
    letra3 = botonC.getText();
    caja = caja + letra3;
    resul.setText(caja);
    }//GEN-LAST:event_botonCActionPerformed

    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra4;
    letra4 = botonD.getText();
    caja = caja + letra4;
    resul.setText(caja);
    }//GEN-LAST:event_botonDActionPerformed

    private void botonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEActionPerformed
        // TODO add your handling code here:
           String caja;
    caja = resul.getText();
    String letra5;
    letra5 = botonE.getText();
    caja = caja + letra5;
    resul.setText(caja);
    }//GEN-LAST:event_botonEActionPerformed

    private void botonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra6;
    letra6 = botonF.getText();
    caja = caja + letra6;
    resul.setText(caja);
    }//GEN-LAST:event_botonFActionPerformed

    private void botonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra7;
    letra7 = botonG.getText();
    caja = caja + letra7;
    resul.setText(caja);
    }//GEN-LAST:event_botonGActionPerformed

    private void botonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHActionPerformed
        // TODO add your handling code here:
          String caja;
    caja = resul.getText();
    String letra8;
    letra8 = botonH.getText();
    caja = caja + letra8;
    resul.setText(caja);
                        
    }//GEN-LAST:event_botonHActionPerformed

    private void botonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra9;
    letra9 = botonI.getText();
    caja = caja + letra9;
    resul.setText(caja);
    }//GEN-LAST:event_botonIActionPerformed

    private void botonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra10;
    letra10 = botonJ.getText();
    caja = caja + letra10;
    resul.setText(caja);
    }//GEN-LAST:event_botonJActionPerformed

    private void botonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra12;
    letra12 = botonL.getText();
    caja = caja + letra12;
    resul.setText(caja);
    }//GEN-LAST:event_botonLActionPerformed

    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra13;
    letra13 = botonM.getText();
    caja = caja + letra13;
    resul.setText(caja);
    }//GEN-LAST:event_botonMActionPerformed

    private void botonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra14;
    letra14 = botonN.getText();
    caja = caja + letra14;
    resul.setText(caja);
    }//GEN-LAST:event_botonNActionPerformed

    private void botonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra15;
    letra15 = botonO.getText();
    caja = caja + letra15;
    resul.setText(caja);
    }//GEN-LAST:event_botonOActionPerformed

    private void botonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPActionPerformed
        // TODO add your handling code here:
           String caja;
    caja = resul.getText();
    String letra16;
    letra16 = botonP.getText();
    caja = caja + letra16;
    resul.setText(caja);
    }//GEN-LAST:event_botonPActionPerformed

    private void botonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra17;
    letra17 = botonQ.getText();
    caja = caja + letra17;
    resul.setText(caja);
    }//GEN-LAST:event_botonQActionPerformed

    private void botonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra18;
    letra18 = botonR.getText();
    caja = caja + letra18;
    resul.setText(caja);
    }//GEN-LAST:event_botonRActionPerformed

    private void botonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSActionPerformed
        // TODO add your handling code here:
          String caja;
    caja = resul.getText();
    String letra19;
    letra19 = botonS.getText();
    caja = caja + letra19;
    resul.setText(caja);
    }//GEN-LAST:event_botonSActionPerformed

    private void botonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTActionPerformed
        // TODO add your handling code here:
          String caja;
    caja = resul.getText();
    String letra20;
    letra20 = botonT.getText();
    caja = caja + letra20;
    resul.setText(caja);
    }//GEN-LAST:event_botonTActionPerformed

    private void botonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUActionPerformed
        // TODO add your handling code here:
          String caja;
    caja = resul.getText();
    String letra21;
    letra21 = botonU.getText();
    caja = caja + letra21;
    resul.setText(caja);
    }//GEN-LAST:event_botonUActionPerformed

    private void botonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra22;
    letra22 = botonV.getText();
    caja = caja + letra22;
    resul.setText(caja);
    }//GEN-LAST:event_botonVActionPerformed

    private void botonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonWActionPerformed
        // TODO add your handling code here:
        String caja;
    caja = resul.getText();
    String letra23;
    letra23 = botonW.getText();
    caja = caja + letra23;
    resul.setText(caja);
    }//GEN-LAST:event_botonWActionPerformed

    private void botonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXActionPerformed
        // TODO add your handling code here:
             String caja;
    caja = resul.getText();
    String letra24;
    letra24 = botonX.getText();
    caja = caja + letra24;
    resul.setText(caja);
    }//GEN-LAST:event_botonXActionPerformed

    private void botonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYActionPerformed
        // TODO add your handling code here:
           String caja;
    caja = resul.getText();
    String letra25;
    letra25 = botonY.getText();
    caja = caja + letra25;
    resul.setText(caja);
    }//GEN-LAST:event_botonYActionPerformed

    private void botonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonZActionPerformed
        // TODO add your handling code here:
         String caja;
    caja = resul.getText();
    String letra26;
    letra26 = botonZ.getText();
    caja = caja + letra26;
    resul.setText(caja);
    }//GEN-LAST:event_botonZActionPerformed

    private void resulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formando_Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formando_Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formando_Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formando_Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formando_Palabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonA;
    private javax.swing.JButton botonB;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonD;
    private javax.swing.JButton botonE;
    private javax.swing.JButton botonF;
    private javax.swing.JButton botonG;
    private javax.swing.JButton botonH;
    private javax.swing.JButton botonI;
    private javax.swing.JButton botonJ;
    private javax.swing.JButton botonK;
    private javax.swing.JButton botonL;
    private javax.swing.JButton botonM;
    private javax.swing.JButton botonN;
    private javax.swing.JButton botonO;
    private javax.swing.JButton botonP;
    private javax.swing.JButton botonQ;
    private javax.swing.JButton botonR;
    private javax.swing.JButton botonS;
    private javax.swing.JButton botonT;
    private javax.swing.JButton botonU;
    private javax.swing.JButton botonV;
    private javax.swing.JButton botonW;
    private javax.swing.JButton botonX;
    private javax.swing.JButton botonY;
    private javax.swing.JButton botonZ;
    private javax.swing.JButton jButton27;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resul;
    // End of variables declaration//GEN-END:variables
}
