
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Parrafos_Menus extends javax.swing.JFrame {

    /**
     * Creates new form Parrafos_Menus
     */
    public Parrafos_Menus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtparrafo1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtparrafo2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtparrafo3 = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Union = new javax.swing.JCheckBoxMenuItem();
        parra_mayor = new javax.swing.JCheckBoxMenuItem();
        parra_menor = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE PARRAFO A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 81, -1, -1));
        getContentPane().add(txtparrafo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 101, 230, -1));

        jLabel2.setText("INGRESE PARRAFO B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 139, -1, -1));
        getContentPane().add(txtparrafo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 171, 230, -1));

        jLabel3.setText("INGRESE PARRAFO C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 219, -1, -1));

        jLabel4.setText("RESULTADO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 307, -1, -1));
        getContentPane().add(txtparrafo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 244, 220, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 339, 260, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        jMenu1.setText("OPERACIONES");

        Union.setSelected(true);
        Union.setText("Unir Parrafos");
        Union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnionActionPerformed(evt);
            }
        });
        jMenu1.add(Union);

        parra_mayor.setSelected(true);
        parra_mayor.setText("Parrafo Mayor");
        parra_mayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parra_mayorActionPerformed(evt);
            }
        });
        jMenu1.add(parra_mayor);

        parra_menor.setSelected(true);
        parra_menor.setText("Parrafo Menor");
        parra_menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parra_menorActionPerformed(evt);
            }
        });
        jMenu1.add(parra_menor);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnionActionPerformed
        // TODO add your handling code here:
        String parrafo1,parrafo2,parrafo3,resultado;
    parrafo1 = txtparrafo1.getText();
    parrafo2 = txtparrafo2.getText();
    parrafo3 = txtparrafo3.getText();
    
    resultado = parrafo1 + parrafo2 + parrafo3;
    resul.setText(resultado);
    }//GEN-LAST:event_UnionActionPerformed

    private void parra_mayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parra_mayorActionPerformed
        // TODO add your handling code here:
        String parrafo1,parrafo2,parrafo3,resultado="";
    int longi1,longi2,longi3;
    parrafo1=txtparrafo1.getText();
    parrafo2=txtparrafo2.getText();
    parrafo3 = txtparrafo3.getText();
    
    longi1 = parrafo1.length();
    longi2 = parrafo2.length();
    longi3 = parrafo3.length();  

       if(longi1 > longi2 || longi1 > longi3){
 resultado = parrafo1;
 }
 else if(longi2 > longi1 || longi2 > longi3){
 resultado = parrafo2;
 }
 else if(longi3 > longi1 || longi3 >longi2){
 resultado = parrafo3;
 }
 else if(longi2 == longi3){
 JOptionPane.showMessageDialog(null, "Hay dos párrafos con la misma longitud");
 }
 else if(longi2 == longi1){
 JOptionPane.showMessageDialog(null, "Hay dos párrafos con la misma longitud");
 }
 else if(longi3 == longi1){
 JOptionPane.showMessageDialog(null, "Hay dos párrafos con la misma longitud");
 } 
 resul.setText(resultado);
    }//GEN-LAST:event_parra_mayorActionPerformed

    private void parra_menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parra_menorActionPerformed
        // TODO add your handling code here:
        String parrafo1,parrafo2,parrafo3,resultado="";
    int longi1,longi2,longi3;
    parrafo1=txtparrafo1.getText();
    parrafo2=txtparrafo2.getText();
    parrafo3 = txtparrafo3.getText();
    
    longi1 = parrafo1.length();
    longi2 = parrafo2.length();
    longi3 = parrafo3.length();
    
     if(longi1 < longi2 || longi1 < longi3){
 resultado = parrafo1;  
 }
 else if(longi2 < longi1 || longi2 < longi3){
 resultado = parrafo2;
 }
 else if(longi3 < longi1 || longi3 < longi2){
 resultado = parrafo3;
 }
 else if(longi2 == longi3){
 JOptionPane.showMessageDialog(null, "Hay dos párrafos con la misma longitud");
 }
 else if(longi2 == longi1){
 JOptionPane.showMessageDialog(null, "Hay dos párrafos con la misma longitud");
 }
 else if(longi3 == longi1){
 JOptionPane.showMessageDialog(null, "Hay dos párrafos con la misma longitud");
 } 
 resul.setText(resultado);
 
    }//GEN-LAST:event_parra_menorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parrafos_Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parrafos_Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parrafos_Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parrafos_Menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parrafos_Menus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Union;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBoxMenuItem parra_mayor;
    private javax.swing.JCheckBoxMenuItem parra_menor;
    private javax.swing.JTextField resul;
    private javax.swing.JTextField txtparrafo1;
    private javax.swing.JTextField txtparrafo2;
    private javax.swing.JTextField txtparrafo3;
    // End of variables declaration//GEN-END:variables
}
