
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Fecha_Nacimiento extends javax.swing.JFrame {

    /**
     * Creates new form Fecha_Nacimiento
     */
    public Fecha_Nacimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtfecha = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE SU FECHA DE NACIMINETO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 78, -1, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 134, -1, -1));

        jLabel2.setText("RESULTADO ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 170, -1));
        jPanel1.add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
               String fecha=""; String dia="", diasn="", mes="", anio="", f="", g="";
        try{
            fecha=txtfecha.getText();

            if(fecha.charAt(0)=='0'){
                switch(fecha.charAt(1)){
                    case '1':
                        dia="Lunes";
                        break;
                    case '2':
                        dia="Martes";
                        break;
                    case '3':
                        dia="Miércoles";
                        break;
                    case '4':
                        dia="Jueves";
                        break;
                    case '5':
                        dia="Viernes";
                        break;
                    case '6':
                        dia="Sábado";
                        break;
                    case '7':
                        dia="Domingo";
                }
            }
            if(fecha.charAt(3)=='0'){
                switch(fecha.charAt(4)){
                    case '1':
                        diasn="Uno";
                        break;
                    case '2':
                        diasn="Dos";
                        break;
                    case '3':
                        diasn="Tres";
                        break;
                    case '4':
                        diasn="Cuatro";
                        break;
                    case '5':
                        diasn="Cinco";
                        break;
                    case '6':
                        diasn="Seis";
                        break;
                    case '7':
                        diasn="Siete";
                        break;
                    case '8':
                        diasn="Ocho";
                        break;
                    case '9':
                        diasn="Nueve";
                        break;
                }
            }
            if(fecha.charAt(3)=='1'){
                switch(fecha.charAt(4)){
                    case '0':
                        diasn="Diez";
                        break;
                    case '1':
                        diasn="Once";
                        break;
                    case '2':
                        diasn="Doce";
                        break;
                    case '3':
                        diasn="Trece";
                        break;
                    case '4':
                        diasn="Catorce";
                        break;
                    case '5':
                        diasn="Quince";
                        break;
                    case '6':
                        diasn="Dieciseis";
                        break;
                    case '7':
                        diasn="Diecisiete";
                        break;
                    case '8':
                        diasn="Dieciocho";
                        break;
                    case '9':
                        diasn="Diecinueve";
                        break;
                }
            }
            if(fecha.charAt(3)=='2'){
                switch(fecha.charAt(4)){
                    case '0':
                        diasn="Veinte";
                        break;
                    case '1':
                        diasn="Veintiuno";
                        break;
                    case '2':
                        diasn="Veintidos";
                        break;
                    case '3':
                        diasn="Veintitres";
                        break;
                    case '4':
                        diasn="Veinticuatro";
                        break;
                    case '5':
                        diasn="Veinticinco";
                        break;
                    case '6':
                        diasn="Veintiseis";
                        break;
                    case '7':
                        diasn="Veintisiete";
                        break;
                    case '8':
                        diasn="Veintiocho";
                        break;
                    case '9':
                        diasn="Veintinueve";
                        break;
                }
            }  
            if(fecha.charAt(3)=='3'){
                switch(fecha.charAt(4)){
                    case '0':
                        diasn="Treinta";
                        break;
                    case '1':
                        diasn="Treinta y uno";
                        break;
                }
            }    
            if(fecha.charAt(6)=='0'){
                switch(fecha.charAt(7)){
                    case '1':
                        mes="De Enero";
                        break;
                    case '2':
                        mes="De Febrero";
                        break;
                    case '3':
                        mes="De Marzo";
                        break;
                    case '4':
                        mes="De Abril";
                        break;
                    case '5':
                        mes="De Mayo";
                        break;
                    case '6':
                        diasn="De Junio";
                        break;
                    case '7':
                        mes="De Julio";
                        break;
                    case '8':
                        mes="De Agosto";
                        break;
                    case '9':
                        mes="De Septiembre";
                        break;
                }
            }
            if(fecha.charAt(6)=='1'){
                switch(fecha.charAt(7)){
                    case '0':
                        mes="De Octubre";
                        break;
                    case '1':
                        mes="De Noviembre";
                        break;
                    case '2':
                        mes="De Diciembre";
                        break;
                }
            }
            char y;
            for(int i=9; i<=12; i++){
                y=fecha.charAt(i);
                anio=anio+y;
            }
          
            
            }
        catch(Exception e){
            
        JOptionPane.showMessageDialog(null, e);
        }

 
                   resul.setText(dia+" "+diasn+" "+mes+" de "+anio);
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fecha_Nacimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fecha_Nacimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fecha_Nacimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fecha_Nacimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fecha_Nacimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resul;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
