/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * DIANA CAROLINA VICTORES ROMERO
 * 9959-19-1471
 * SEGUNDO PARCIAL 08/10/2020
 * @author Diana
 */
public class SEGUNDO_PARCIAL extends javax.swing.JFrame {

    /**
     * Creates new form SEGUNDO_PARCIAL
     */
    public SEGUNDO_PARCIAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtparrafo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        resultadovocales = new javax.swing.JTextField();
        resultadonumeros = new javax.swing.JTextField();
        resultadoconsonantes = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        VOCALESS = new javax.swing.JMenu();
        vocales = new javax.swing.JCheckBoxMenuItem();
        DIGITOS = new javax.swing.JCheckBoxMenuItem();
        consonantes = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE PARRAFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 52, -1, -1));

        jLabel2.setText("VOCALES EN EL PARRAFO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 138, -1, -1));

        jLabel3.setText("NUMEROS EN EL PARRAFO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 176, -1, -1));

        jLabel4.setText("CONSONANTES EN EL PARRAFO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 214, -1, -1));
        getContentPane().add(txtparrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 52, 232, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("DIANA CAROLINA VICTORES ROMERO 9959-19-1471");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));
        jPanel1.add(resultadovocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 114, -1));
        jPanel1.add(resultadonumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 114, -1));
        jPanel1.add(resultadoconsonantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 114, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 370));

        VOCALESS.setText("INDICADORES");

        vocales.setSelected(true);
        vocales.setText("VOCALES");
        vocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalesActionPerformed(evt);
            }
        });
        VOCALESS.add(vocales);

        DIGITOS.setSelected(true);
        DIGITOS.setText("NUMEROS");
        DIGITOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIGITOSActionPerformed(evt);
            }
        });
        VOCALESS.add(DIGITOS);

        consonantes.setSelected(true);
        consonantes.setText("CONSONANTES");
        consonantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consonantesActionPerformed(evt);
            }
        });
        VOCALESS.add(consonantes);

        jMenuBar1.add(VOCALESS);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalesActionPerformed
        // TODO add your handling code here:
        String parrafo,newparra="";
        char caracter;
        int h,longi;

        parrafo = txtparrafo.getText();
        longi = parrafo.length();

        for(h=0;h<longi;h++){
        caracter = parrafo.charAt(h);

        if(caracter != 'b'&& caracter != 'c'&& caracter != 'd'&& caracter != 'f'&& caracter != 'g'&& caracter != 'h'&& caracter != 'j'&& caracter != 'k'&& caracter != 'l'&& caracter != 'm'&& caracter != 'n'&& caracter != 'p'&& caracter != 'q'&& caracter != 'r'&& caracter != 's'&& caracter != 't'&& caracter != 'v'&& caracter != 'w'&& caracter != 'x'&& caracter != 'y'&& caracter != 'z'&& caracter != 'ñ'&& caracter != '1'&& caracter != '2'&& caracter != '3'&& caracter != '4'&& caracter != '5'&& caracter != '6'&& caracter != '7'&& caracter != '8'&& caracter != '9'&& caracter != '0'&& caracter != ' '){
        newparra = newparra + caracter;
        }
        }

        resultadovocales.setText(newparra);
           
    }//GEN-LAST:event_vocalesActionPerformed

    private void DIGITOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIGITOSActionPerformed
        // TODO add your handling code here:
       String parrafo,newparra="";
        char caracter;
        int x,longi;

        parrafo = txtparrafo.getText();
        longi = parrafo.length();

        for(x=0;x<longi;x++){
        caracter = parrafo.charAt(x);

        if(caracter != 'a' && caracter != 'e' && caracter != 'i' && caracter != 'o'&& caracter != 'u'&& caracter != 'b'&& caracter != 'c'&& caracter != 'd'&& caracter != 'f'&& caracter != 'g'&& caracter != 'h'&& caracter != 'j'&& caracter != 'k'&& caracter != 'l'&& caracter != 'm'&& caracter != 'n'&& caracter != 'p'&& caracter != 'q'&& caracter != 'r'&& caracter != 's'&& caracter != 't'&& caracter != 'v'&& caracter != 'w'&& caracter != 'x'&& caracter != 'y'&& caracter != 'z'&& caracter != 'ñ'&& caracter != ' '){
        newparra = newparra + caracter;
        }
        }

    resultadonumeros.setText(newparra);
    
    }//GEN-LAST:event_DIGITOSActionPerformed

    private void consonantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consonantesActionPerformed
        // TODO add your handling code here:
   String parrafo,newparra="";
    char caracter;
    int h,longi;

    parrafo = txtparrafo.getText();
    longi = parrafo.length();

    for(h=0;h<longi;h++){
    caracter = parrafo.charAt(h);

    if(caracter != 'a' && caracter != 'e' && caracter != 'i' && caracter != 'o'&& caracter != 'u'&& caracter != '1'&& caracter != '2'&& caracter != '3'&& caracter != '4'&& caracter != '5'&& caracter != '6'&& caracter != '7'&& caracter != '8'&& caracter != '9'&& caracter != '0'&& caracter != ' '){
    newparra = newparra + caracter;
    }
    }


       resultadoconsonantes.setText(newparra);
        
    }//GEN-LAST:event_consonantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEGUNDO_PARCIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEGUNDO_PARCIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEGUNDO_PARCIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEGUNDO_PARCIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEGUNDO_PARCIAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem DIGITOS;
    private javax.swing.JMenu VOCALESS;
    private javax.swing.JCheckBoxMenuItem consonantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resultadoconsonantes;
    private javax.swing.JTextField resultadonumeros;
    private javax.swing.JTextField resultadovocales;
    private javax.swing.JTextField txtparrafo;
    private javax.swing.JCheckBoxMenuItem vocales;
    // End of variables declaration//GEN-END:variables
}
