
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class progresbar_conti extends javax.swing.JFrame {
     float nume1,nume2,nume3,resul;
    /**
     * Creates new form progresbar_conti
     */
    public progresbar_conti() {
        initComponents();
        pb1.setStringPainted(true);
        pb1.setForeground(Color.green);
        pb2.setStringPainted(true);
        pb2.setForeground(Color.green);
        pb3.setStringPainted(true);
        pb3.setForeground(Color.green);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pb2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        pb3 = new javax.swing.JProgressBar();
        menorbarra1 = new javax.swing.JButton();
        mayorbarra1 = new javax.swing.JButton();
        menorbarra2 = new javax.swing.JButton();
        mayorbarra2 = new javax.swing.JButton();
        menorbarra3 = new javax.swing.JButton();
        mayorbarra3 = new javax.swing.JButton();
        resulbarra1 = new javax.swing.JTextField();
        resulbarra2 = new javax.swing.JTextField();
        resulbarra3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        result = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BARRA 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 38, -1, -1));
        getContentPane().add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 64, 208, -1));

        jLabel2.setText("BARRA 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 144, -1, -1));
        getContentPane().add(pb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 186, 208, -1));

        jLabel3.setText("BARRA 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 281, -1, -1));
        getContentPane().add(pb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 319, 208, -1));

        menorbarra1.setText("-");
        menorbarra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorbarra1ActionPerformed(evt);
            }
        });
        getContentPane().add(menorbarra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 89, -1, -1));

        mayorbarra1.setText("+");
        mayorbarra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorbarra1ActionPerformed(evt);
            }
        });
        getContentPane().add(mayorbarra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 89, -1, -1));

        menorbarra2.setText("-");
        menorbarra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorbarra2ActionPerformed(evt);
            }
        });
        getContentPane().add(menorbarra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 218, -1, -1));

        mayorbarra2.setText("+");
        mayorbarra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorbarra2ActionPerformed(evt);
            }
        });
        getContentPane().add(mayorbarra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 218, -1, -1));

        menorbarra3.setText("-");
        menorbarra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorbarra3ActionPerformed(evt);
            }
        });
        getContentPane().add(menorbarra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 351, -1, -1));

        mayorbarra3.setText("+");
        mayorbarra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorbarra3ActionPerformed(evt);
            }
        });
        getContentPane().add(mayorbarra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 351, -1, -1));
        getContentPane().add(resulbarra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 58, 51, -1));
        getContentPane().add(resulbarra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 180, 51, -1));
        getContentPane().add(resulbarra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 313, 51, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 451, -1, -1));
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 452, 51, -1));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menorbarra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorbarra1ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb1.getValue()-1;
        if(valor<pb1.getMinimum()){
        valor=pb1.getMinimum();
        }
        pb1.setValue(valor);
        resulbarra1.setText(String.valueOf(valor));
    }//GEN-LAST:event_menorbarra1ActionPerformed

    private void mayorbarra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorbarra1ActionPerformed
        // TODO add your handling code here:
         int valor = 0;
        valor = pb1.getValue() + 1;
        if(valor>pb1.getMaximum()){
        valor=pb1.getMaximum();
          }
        pb1.setValue(valor);
        resulbarra1.setText(String.valueOf(valor));
    }//GEN-LAST:event_mayorbarra1ActionPerformed

    private void menorbarra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorbarra2ActionPerformed
        // TODO add your handling code here:
         int valor = 0;
        valor = pb2.getValue()-1;
        if(valor<pb2.getMinimum()){
        valor=pb2.getMinimum();
        }
        pb2.setValue(valor);
        resulbarra2.setText(String.valueOf(valor));
    }//GEN-LAST:event_menorbarra2ActionPerformed

    private void mayorbarra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorbarra2ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb2.getValue() + 1;
        if(valor>pb2.getMaximum()){
        valor=pb2.getMaximum();
          }
        pb2.setValue(valor);
        resulbarra2.setText(String.valueOf(valor));
    }//GEN-LAST:event_mayorbarra2ActionPerformed

    private void menorbarra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorbarra3ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb3.getValue()-1;
        if(valor<pb3.getMinimum()){
        valor=pb3.getMinimum();
        }
        pb3.setValue(valor);
        resulbarra3.setText(String.valueOf(valor));
    }//GEN-LAST:event_menorbarra3ActionPerformed

    private void mayorbarra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorbarra3ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb3.getValue() + 1;
        if(valor>pb3.getMaximum()){
        valor=pb3.getMaximum();
          }
        pb3.setValue(valor);
        resulbarra3.setText(String.valueOf(valor));
    }//GEN-LAST:event_mayorbarra3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //SUMA
        nume1= Float.parseFloat(resulbarra1.getText());
        nume2=Float.parseFloat(resulbarra2.getText());
        nume3=Float.parseFloat(resulbarra3.getText());
        resul=nume1+nume2+nume3;
        result.setText(String.valueOf(resul));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progresbar_conti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progresbar_conti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progresbar_conti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progresbar_conti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progresbar_conti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mayorbarra1;
    private javax.swing.JButton mayorbarra2;
    private javax.swing.JButton mayorbarra3;
    private javax.swing.JButton menorbarra1;
    private javax.swing.JButton menorbarra2;
    private javax.swing.JButton menorbarra3;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JProgressBar pb2;
    private javax.swing.JProgressBar pb3;
    private javax.swing.JTextField resulbarra1;
    private javax.swing.JTextField resulbarra2;
    private javax.swing.JTextField resulbarra3;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
