
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class PROGRESSBAR extends javax.swing.JFrame {

    /**
     * Creates new form PROGRESSBAR
     */
    public PROGRESSBAR() {
        initComponents();
        pb3.setStringPainted(true);
        pb3.setForeground(Color.blue);
       pb4.setStringPainted(true);
       pb4.setForeground(Color.red);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        pb2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        ver = new javax.swing.JButton();
        resulbarra2 = new javax.swing.JTextField();
        menor = new javax.swing.JButton();
        pb3 = new javax.swing.JProgressBar();
        mayor = new javax.swing.JButton();
        mayorbarra3 = new javax.swing.JButton();
        menorbarra3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pb4 = new javax.swing.JProgressBar();
        menorbarra4 = new javax.swing.JButton();
        mayorbarra4 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BARRA 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 38, -1, -1));
        getContentPane().add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 63, 257, 25));

        jLabel2.setText("BARRA 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 134, -1, -1));
        getContentPane().add(pb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 166, 257, 27));

        jLabel3.setText("BARRA 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        ver.setText("VER");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        getContentPane().add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 65, -1, -1));
        getContentPane().add(resulbarra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 166, 51, -1));

        menor.setText("<");
        menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorActionPerformed(evt);
            }
        });
        getContentPane().add(menor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 211, -1, -1));

        pb3.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(pb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 302, 257, 24));

        mayor.setText(">");
        mayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorActionPerformed(evt);
            }
        });
        getContentPane().add(mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 211, -1, -1));

        mayorbarra3.setText(">");
        mayorbarra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorbarra3ActionPerformed(evt);
            }
        });
        getContentPane().add(mayorbarra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        menorbarra3.setText("<");
        menorbarra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorbarra3ActionPerformed(evt);
            }
        });
        getContentPane().add(menorbarra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 344, -1, -1));

        jLabel4.setText("BARRA 4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pb4.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(pb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 250, 30));

        menorbarra4.setText("<");
        menorbarra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorbarra4ActionPerformed(evt);
            }
        });
        jPanel1.add(menorbarra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 505, -1, -1));

        mayorbarra4.setText(">");
        mayorbarra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorbarra4ActionPerformed(evt);
            }
        });
        jPanel1.add(mayorbarra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 505, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
        int valor = 60;
        pb1.setValue(valor);
    }//GEN-LAST:event_verActionPerformed

    private void menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb2.getValue()-10;
        if(valor<pb2.getMinimum()){
        valor=pb2.getMinimum();
        }
        pb2.setValue(valor);
        resulbarra2.setText(String.valueOf(valor));
    }//GEN-LAST:event_menorActionPerformed

    private void mayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb2.getValue() + 5;
        if(valor>pb2.getMaximum()){
        valor=pb2.getMaximum();
          }
        pb2.setValue(valor);
        resulbarra2.setText(String.valueOf(valor));
    }//GEN-LAST:event_mayorActionPerformed

    private void menorbarra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorbarra3ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb3.getValue()-10;
        if(valor<pb3.getMinimum()){
        valor=pb3.getMinimum();
        }
        pb3.setValue(valor);
    }//GEN-LAST:event_menorbarra3ActionPerformed

    private void mayorbarra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorbarra3ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb3.getValue() + 5;
        if(valor>pb3.getMaximum()){
        valor=pb3.getMaximum();
        }
      
        pb3.setValue(valor);
    }//GEN-LAST:event_mayorbarra3ActionPerformed

    private void menorbarra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorbarra4ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb4.getValue()-2;
        if(valor<pb4.getMinimum()){
        valor=pb4.getMinimum();
        }
        pb4.setValue(valor);
    }//GEN-LAST:event_menorbarra4ActionPerformed

    private void mayorbarra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorbarra4ActionPerformed
        // TODO add your handling code here:
        int valor = 0;
        valor = pb4.getValue() + 3;
        if(valor>pb4.getMaximum()){
        valor=pb4.getMaximum();
        }
       
        pb4.setValue(valor);
    }//GEN-LAST:event_mayorbarra4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROGRESSBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROGRESSBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROGRESSBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROGRESSBAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROGRESSBAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mayor;
    private javax.swing.JButton mayorbarra3;
    private javax.swing.JButton mayorbarra4;
    private javax.swing.JButton menor;
    private javax.swing.JButton menorbarra3;
    private javax.swing.JButton menorbarra4;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JProgressBar pb2;
    private javax.swing.JProgressBar pb3;
    private javax.swing.JProgressBar pb4;
    private javax.swing.JTextField resulbarra2;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
