
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class characters_search extends javax.swing.JFrame {

    /**
     * Creates new form characters_search
     */
    public characters_search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtparra = new javax.swing.JTextField();
        txtletra = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ulet = new javax.swing.JTextField();
        plet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE PARRAFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 76, -1, -1));

        jLabel2.setText("CARACTER A BUSCAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 129, -1, -1));

        jLabel3.setText("CANTIDAD DE PALABRAS CON ESE CARACTER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 243, -1, -1));
        getContentPane().add(txtparra, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 73, 215, -1));
        getContentPane().add(txtletra, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 126, 90, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 263, 70, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel4.setText("ULTIMA LETRA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel5.setText("PRIMERA LETRA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));
        jPanel1.add(ulet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 120, -1));
        jPanel1.add(plet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String parra;
//String newparra="";
//int palabras=0;
//int totalcaracter=0;
//String palabra;
//palabra = txtparra.getText();
//parra = txtletra.getText();
//StringTokenizer st = new StringTokenizer(parra," ");
//while (st.hasMoreTokens()) {
////System.out.println(st.nextToken());
//newparra = newparra + st.nextToken() ;
//// busque el caracter desde la posicion 0
//totalcaracter = newparra.indexOf(palabra,0);
//// si la posicion es diferente de -1 lo encontro entonces suma
//if(totalcaracter > -1){
//palabras = palabras + 1;
//}
//newparra = "";
//}
//resul.setText(Integer.toString(palabras));


//CODIGO PARA CALCULAR TOTAL DE LETRAS
String parra,le;
        char ch, ch2;
        int total=0, longi,i;
        parra=txtparra.getText();
        le=txtletra.getText();
        ch2=le.charAt(0);
        longi=parra.length();
        for (i=0; i<longi; i=i+1){
            
            ch=parra.charAt(i);
            if (ch==ch2)
                {
                    total=total+1;
                    resul.setText(String.valueOf(total));
                }
  
                }
        // CPRIMERAS LETRAS Y ULTIMAS LETRAS DE CADA PALABRA
         String parrafo,newpal="",ultimas=" ",primeras="";
        char ch1,prl,ul=' ';
        int e,x,longi1,longi2;
       
    parrafo=txtparra.getText();
    longi1=parrafo.length();
    for (e=0;e<longi1;e=e+1){
    ch1=parrafo.charAt(e);
    newpal=newpal+ch1;
    if (ch1==' '){
        prl=newpal.charAt(0);
        longi2=newpal.length()-1;
        ul=newpal.charAt(1);
        ultimas=ultimas+ul;
        primeras=primeras+prl;
        newpal="" ;
        }
    
        
    }
    
         ulet.setText(ultimas);
         plet.setText(primeras);   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(characters_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(characters_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(characters_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(characters_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new characters_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField plet;
    private javax.swing.JTextField resul;
    private javax.swing.JTextField txtletra;
    private javax.swing.JTextField txtparra;
    private javax.swing.JTextField ulet;
    // End of variables declaration//GEN-END:variables
}
