
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class ValoresdeConjunto extends javax.swing.JFrame {

    /**
     * Creates new form ValoresdeConjunto
     */
    public ValoresdeConjunto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pr = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        resul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        voc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidaddedigitos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE CONJUNTO SEPARADO POR COMAS ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 106, -1, -1));
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 131, 224, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("VALORES DE CONJUNTO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel3.setText("CANTIDAD DE ELEMENTOS EN EL CONJUNTO ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 62, -1));

        jLabel4.setText("CANTIDAD DE VOCALES EN EL CONJUNTO ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel1.add(voc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 62, -1));

        jLabel5.setText("CANTIDADES DE DIGITOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        jPanel1.add(cantidaddedigitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 62, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String parra;
      
 String newparra="";
 int palabras=0;
 int vocales = 0;
 int digitos=0;
 
 parra = pr.getText();


 StringTokenizer st = new StringTokenizer(parra,",");
 while (st.hasMoreTokens()) {
 //System.out.println(st.nextToken());

 newparra = newparra + st.nextToken() ;

 if(newparra.equals("a") || newparra.equals("e") || newparra.equals("i") || newparra.equals("o")|| newparra.equals("u")){
 vocales = vocales + 1;

 }

  if(newparra.equals("0") || newparra.equals("1") || newparra.equals("2") || newparra.equals("3")|| newparra.equals("4")|| newparra.equals("5")|| newparra.equals("6")|| newparra.equals("7")|| newparra.equals("8")|| newparra.equals("9")){
 digitos = digitos + 1;

 }

 palabras = palabras + 1;
 newparra = "";
 }
 resul.setText(Integer.toString(palabras));
 voc.setText(Integer.toString(vocales));
 cantidaddedigitos.setText(Integer.toString(digitos));
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoresdeConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoresdeConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoresdeConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoresdeConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoresdeConjunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidaddedigitos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField resul;
    private javax.swing.JTextField voc;
    // End of variables declaration//GEN-END:variables
}
