/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class menuNombre extends javax.swing.JFrame {

    /**
     * Creates new form menuNombre
     */
    public menuNombre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnombre = new javax.swing.JTextField();
        snombre = new javax.swing.JTextField();
        papellido = new javax.swing.JTextField();
        sapellido = new javax.swing.JTextField();
        anio = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        nomcompleto = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        txtiniciales = new javax.swing.JCheckBoxMenuItem();
        txtedad = new javax.swing.JCheckBoxMenuItem();
        txtultimasletras = new javax.swing.JCheckBoxMenuItem();
        txtlongitud = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRIMER NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 74, -1, -1));

        jLabel2.setText("SEGUNDO NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 74, -1, -1));

        jLabel3.setText("PRIMER APELLIDO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 185, -1, -1));

        jLabel4.setText("SEGUNDO APELLIDO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 185, -1, -1));

        jLabel5.setText("AÑO DE NACIMIENTO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 272, -1, -1));
        getContentPane().add(pnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 99, 186, -1));
        getContentPane().add(snombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 99, 169, -1));
        getContentPane().add(papellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 210, 186, -1));
        getContentPane().add(sapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 210, 169, -1));
        getContentPane().add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 297, 105, -1));
        getContentPane().add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 347, 275, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 460));

        nomcompleto.setText("OPERACIONES");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("NOMBRE COMPLETO");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        nomcompleto.add(jCheckBoxMenuItem1);

        txtiniciales.setSelected(true);
        txtiniciales.setText("INICIALES");
        txtiniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicialesActionPerformed(evt);
            }
        });
        nomcompleto.add(txtiniciales);

        txtedad.setSelected(true);
        txtedad.setText("EDAD");
        txtedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedadActionPerformed(evt);
            }
        });
        nomcompleto.add(txtedad);

        txtultimasletras.setSelected(true);
        txtultimasletras.setText("ULTIMAS LETRAS");
        txtultimasletras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtultimasletrasActionPerformed(evt);
            }
        });
        nomcompleto.add(txtultimasletras);

        txtlongitud.setSelected(true);
        txtlongitud.setText("LONGITUD");
        txtlongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlongitudActionPerformed(evt);
            }
        });
        nomcompleto.add(txtlongitud);

        jMenuBar1.add(nomcompleto);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedadActionPerformed
        //EDAD
        String valor;
        int num,edad;
        valor = anio.getText();
        num = Integer.parseInt(valor);
        edad = 2020 - num;
        resul.setText(String.valueOf(edad));
    }//GEN-LAST:event_txtedadActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // NOMBRE COMPLETO
        String parrafo1,parrafo2,parrafo3,parrafo4,parrafo5,resultado;
        parrafo1 = pnombre.getText();
        parrafo2 = snombre.getText();
        parrafo3 = papellido.getText();
        parrafo4 = sapellido.getText();
        parrafo5 = anio.getText();
    
    resultado = parrafo1 + parrafo2 + parrafo3+ parrafo4;
    resul.setText(resultado);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void txtinicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicialesActionPerformed
        // INICIALES
        String nom1,nom2,a1,a2,resultado,iniciales=" ";
        char letra1,letra2,letra3,letra4;
        
        nom1 = pnombre.getText();
        nom2 = snombre.getText();
        a1 = papellido.getText();
        a2 = sapellido.getText();
        
        letra1 =nom1.charAt(0);
        letra2 =nom2.charAt(0);
        letra3 =a1.charAt(0);
        letra4 =a2.charAt(0);
        
        iniciales = iniciales + letra1 + letra2 + letra3 + letra4;
        resultado = resul.getText();
        resultado = resultado + iniciales;
        resul.setText(resultado);
        
      
        
    }//GEN-LAST:event_txtinicialesActionPerformed

    private void txtultimasletrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtultimasletrasActionPerformed
        // ULTIMAS LETRAS
     String nombre1,nombre2,apellido1,apellido2,resultado="",tot;
        int longi1,longi2,longi3,longi4,x,i,z,y;
        char letra1,letra2,letra3,letra4;
        
        nombre1=pnombre.getText();
        nombre2=snombre.getText();
        apellido1=papellido.getText();
        apellido2=sapellido.getText();
        
        longi1=nombre1.length();
        longi2=nombre2.length();
        longi3=apellido1.length();
        longi4=apellido2.length();
        
        x=longi1-1;
        i=longi2-1;
        z=longi3-1;
        y=longi4-1;
        
        letra1 =nombre1.charAt(x);
        letra2 =nombre2.charAt(i);
        letra3 =apellido1.charAt(z);
        letra4 =apellido2.charAt(y);
        
        resultado=resultado+letra1+letra2+letra3+letra4;
        tot=resul.getText();
        tot=tot+resultado;
        resul.setText(String.valueOf(tot));
        
        
        
    }//GEN-LAST:event_txtultimasletrasActionPerformed

    private void txtlongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlongitudActionPerformed
        // LONGITUD
        String num1,num2,tot="";
        int longi1,longi2;
        num1=pnombre.getText();
        num2=snombre.getText();
        longi1=num1.length();
        longi2=num2.length();
        if(longi1>longi2){
        tot=tot+num1;
        }else{
        tot=tot+num2;
        }resul.setText(String.valueOf(tot));
    }//GEN-LAST:event_txtlongitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu nomcompleto;
    private javax.swing.JTextField papellido;
    private javax.swing.JTextField pnombre;
    private javax.swing.JTextField resul;
    private javax.swing.JTextField sapellido;
    private javax.swing.JTextField snombre;
    private javax.swing.JCheckBoxMenuItem txtedad;
    private javax.swing.JCheckBoxMenuItem txtiniciales;
    private javax.swing.JCheckBoxMenuItem txtlongitud;
    private javax.swing.JCheckBoxMenuItem txtultimasletras;
    // End of variables declaration//GEN-END:variables
}
