
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Menu_vocales_numeros extends javax.swing.JFrame {

    /**
     * Creates new form Menu_vocales_numeros
     */
    public Menu_vocales_numeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtparrafo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resultadovocales = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resultadoconsonantes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultadonumeros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resultadoespacionblaanco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        resultadopalabras = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VOCALESS = new javax.swing.JCheckBoxMenuItem();
        CONSONANTESS = new javax.swing.JCheckBoxMenuItem();
        DIGITOS = new javax.swing.JCheckBoxMenuItem();
        ESPACIO_BLANCO = new javax.swing.JCheckBoxMenuItem();
        CANTIDADES = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE PARRAFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 97, -1, -1));
        getContentPane().add(txtparrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 117, 288, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("VOCALES EN EL PARRAFO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(resultadovocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 70, -1));

        jLabel4.setText("CONSONANTES EN EL PARRAFO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));
        jPanel1.add(resultadoconsonantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 70, -1));

        jLabel3.setText("NUMEROS EN EL PARRAFO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(resultadonumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 70, -1));

        jLabel5.setText("ESPACIOS EN BLANCO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));
        jPanel1.add(resultadoespacionblaanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 70, -1));

        jLabel6.setText("CATIDAD DE PALABRAS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        jPanel1.add(resultadopalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jMenu1.setText("INDICADORES");

        VOCALESS.setSelected(true);
        VOCALESS.setText("VOCALES");
        VOCALESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOCALESSActionPerformed(evt);
            }
        });
        jMenu1.add(VOCALESS);

        CONSONANTESS.setSelected(true);
        CONSONANTESS.setText("CONSONATES");
        CONSONANTESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSONANTESSActionPerformed(evt);
            }
        });
        jMenu1.add(CONSONANTESS);

        DIGITOS.setSelected(true);
        DIGITOS.setText("NUMEROS");
        DIGITOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIGITOSActionPerformed(evt);
            }
        });
        jMenu1.add(DIGITOS);

        ESPACIO_BLANCO.setSelected(true);
        ESPACIO_BLANCO.setText("ESPACIOS EN BLANCO");
        ESPACIO_BLANCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESPACIO_BLANCOActionPerformed(evt);
            }
        });
        jMenu1.add(ESPACIO_BLANCO);

        CANTIDADES.setSelected(true);
        CANTIDADES.setText("CANTIDAD DE PALABRAS");
        CANTIDADES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADESActionPerformed(evt);
            }
        });
        jMenu1.add(CANTIDADES);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOCALESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOCALESSActionPerformed
        // VOCALES
        String parrafo;
int totaln=0,x,longi;
char letra;
parrafo = txtparrafo.getText();
longi = parrafo.length();
for(x=0;x<longi;x=x+1){
letra = parrafo.charAt(x);
if(letra=='a' || letra == 'e' || letra == 'i' || letra == 'o' || letra=='u'){
totaln = totaln + 1;
}
}
resultadovocales.setText(String.valueOf(totaln));
    }//GEN-LAST:event_VOCALESSActionPerformed

    private void DIGITOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIGITOSActionPerformed
        // NUMEROS
 String parrafo;
int totaln=0,x,longi;
char letra;
parrafo = txtparrafo.getText();
longi = parrafo.length();
for(x=0;x<longi;x=x+1){
letra = parrafo.charAt(x);
if(letra=='0' || letra == '1' || letra == '2' || letra == '3' || letra=='4' || letra=='5' || letra=='6' || letra=='7' || letra=='8' || letra=='9'){
totaln = totaln + 1;
}
}
 resultadonumeros.setText(Integer.toString(totaln));

   

    }//GEN-LAST:event_DIGITOSActionPerformed

    private void CONSONANTESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSONANTESSActionPerformed
        //CONSONANTES
       String parrafo;
int totaln=0,x,longi;
char letra;
parrafo = txtparrafo.getText();
longi = parrafo.length();
for(x=0;x<longi;x=x+1){
letra = parrafo.charAt(x);
if(letra=='b' || letra == 'c' || letra == 'd' || letra == 'f' || letra=='g' || letra == 'h' || letra == 'j' || letra == 'k' || letra == 'l' || letra == 'm' || letra == 'n' || letra == 'n' || letra == 'p' || letra == 'q' || letra == 'r' || letra == 's' || letra == 't' || letra == 'v' || letra == 'w' || letra == 'x' || letra == 'y' || letra == 'z'){
totaln = totaln + 1;
}
}
resultadoconsonantes.setText(String.valueOf(totaln)); 
        
        
    }//GEN-LAST:event_CONSONANTESSActionPerformed

    private void CANTIDADESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADESActionPerformed
        // CANTIDAD DE PALABRAS
      String parrafo;
      String newparra="";
      int palabra=0;
     parrafo = txtparrafo.getText();

    StringTokenizer st = new StringTokenizer(parrafo," ");
    while (st.hasMoreTokens()) {
    newparra = newparra + st.nextToken() ;
    palabra=palabra + 1;
    }        
    resultadopalabras.setText(Integer.toString(palabra));       
    }//GEN-LAST:event_CANTIDADESActionPerformed

    private void ESPACIO_BLANCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESPACIO_BLANCOActionPerformed
         
          // ESPACIOS EN BLANCO
        String parrafo;
    int totaln=0,x,longi;
    char espacios;

    parrafo = txtparrafo.getText();
    longi = parrafo.length();

    for(x=0;x<longi;x=x+1){
    espacios = parrafo.charAt(x);
    if(espacios==' '){
    totaln = totaln + 1;
    }
    }
    resultadoespacionblaanco.setText(String.valueOf(totaln));
    }//GEN-LAST:event_ESPACIO_BLANCOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_vocales_numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_vocales_numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem CANTIDADES;
    private javax.swing.JCheckBoxMenuItem CONSONANTESS;
    private javax.swing.JCheckBoxMenuItem DIGITOS;
    private javax.swing.JCheckBoxMenuItem ESPACIO_BLANCO;
    private javax.swing.JCheckBoxMenuItem VOCALESS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resultadoconsonantes;
    private javax.swing.JTextField resultadoespacionblaanco;
    private javax.swing.JTextField resultadonumeros;
    private javax.swing.JTextField resultadopalabras;
    private javax.swing.JTextField resultadovocales;
    private javax.swing.JTextField txtparrafo;
    // End of variables declaration//GEN-END:variables
}
