
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Palabra_especifico extends javax.swing.JFrame {

    /**
     * Creates new form Palabra_especifico
     */
    public Palabra_especifico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pr = new javax.swing.JTextField();
        pal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        resul = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtdiagonal = new javax.swing.JRadioButton();
        txtcoma = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        conver = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE PARRAFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 94, -1, -1));

        jLabel2.setText("PALABRA A BUSCAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 178, -1, -1));
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 91, 168, -1));
        getContentPane().add(pal, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 175, 168, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("CANTIDAD DE VECES QUE APARECE LA PALABRA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        resul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resulActionPerformed(evt);
            }
        });
        jPanel1.add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 44, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdiagonal.setText("/");
        jPanel2.add(txtdiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));

        txtcoma.setText(",");
        jPanel2.add(txtcoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 43, -1, -1));

        jLabel4.setText("SIMBOLOS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 130, 70));

        jLabel5.setText("ESPACIOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 20));
        jPanel1.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 60, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel6.setText("CONVERTIDO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));
        jPanel1.add(conver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 220, 30));

        jButton2.setText("CONVERTIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // inicializo las variables a utilizar
        // inicializo las variables a utilizar
        String parra;
        String newparra="";
        int palabras=0;
        String palabra;
        char ch;
        // realizo el traslado de lo que ingrese en los textfield
        // hacia el código de mi programa a través de getText()
        palabra = pal.getText();
        parra = pr.getText();
        // utilizo la instruccion StringTokenizer para definer un
        // valor que en este caso defino como “st” para identificar
        // los fragmentos del párrafo separados por espacio en bla
        StringTokenizer st = new StringTokenizer(parra," ");
        // mientras existan tokens(fragmentos) entre al ciclo
        while (st.hasMoreTokens()) {
        // el fragmento que va apareciendo pegarlo a newparra
        newparra = newparra + st.nextToken() ;
        // si la palabra ingresada es igual al fragmento
        // entonces sume el contador a palabras
        if (palabra.equals(newparra)){
        palabras = palabras + 1;
        }
        // vuelva a colocar un valor nulo a newparra
        // para que coloque ahí el nuevo fragmento
        newparra = "";
        }
        // envie el resultado a la ventana
        resul.setText(Integer.toString(palabras));
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String num;
        int  espacios,cont,i;
         int longi;
        String palabra="",newpal="",diagonal="", coma="";
        char ch;
       
        palabra=pr.getText();
        longi=palabra.length();
        num=n.getText();
        espacios=Integer.parseInt(num);
        cont=0;
         
       if(txtdiagonal.isSelected()){
    for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;  
       
         if (cont==espacios){
        newpal=newpal+"/";
        cont=0;
    }
    }
     }
         
           if (txtcoma.isSelected()){
   for(i=0;i<longi;i=i+1){
       ch= palabra.charAt(i);
       newpal=newpal+ch;
       cont=cont+1;
    
    if (cont==espacios){
        newpal=newpal+",";
        cont=0;
    }
    }
    }
            conver.setText(newpal);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Palabra_especifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Palabra_especifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Palabra_especifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Palabra_especifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Palabra_especifico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField n;
    private javax.swing.JTextField pal;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField resul;
    private javax.swing.JRadioButton txtcoma;
    private javax.swing.JRadioButton txtdiagonal;
    // End of variables declaration//GEN-END:variables
}
