/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class menu_operaciones extends javax.swing.JFrame {

    /**
     * Creates new form menu_operaciones
     */
    public menu_operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvalor1 = new javax.swing.JTextField();
        txtvalor2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtresultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        operaciones = new javax.swing.JMenu();
        txtsuma = new javax.swing.JCheckBoxMenuItem();
        RESTA = new javax.swing.JCheckBoxMenuItem();
        DIVISION = new javax.swing.JCheckBoxMenuItem();
        MULTIPLICACION = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VALOR 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VALOR 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 121, -1, -1));
        getContentPane().add(txtvalor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 67, 53, -1));
        getContentPane().add(txtvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 118, 53, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESULTADO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 330));

        operaciones.setText("OPERACIONES");

        txtsuma.setSelected(true);
        txtsuma.setText("SUMA");
        txtsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsumaActionPerformed(evt);
            }
        });
        operaciones.add(txtsuma);

        RESTA.setSelected(true);
        RESTA.setText("RESTA");
        RESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTAActionPerformed(evt);
            }
        });
        operaciones.add(RESTA);

        DIVISION.setSelected(true);
        DIVISION.setText("DIVISION");
        DIVISION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVISIONActionPerformed(evt);
            }
        });
        operaciones.add(DIVISION);

        MULTIPLICACION.setSelected(true);
        MULTIPLICACION.setText("MULTIPLICACION");
        MULTIPLICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTIPLICACIONActionPerformed(evt);
            }
        });
        operaciones.add(MULTIPLICACION);

        jMenuBar1.add(operaciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsumaActionPerformed
        // TODO add your handling code here:
        String num1,num2;
int n1,n2,total;
num1 = txtvalor1.getText();
num2 = txtvalor2.getText();
n1 = Integer.parseInt(num1);
n2 = Integer.parseInt(num2);
total = n1 + n2;
txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_txtsumaActionPerformed

    private void RESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAActionPerformed
        // TODO add your handling code here:
        String num1,num2;
int n1,n2,total;
num1 = txtvalor1.getText();
num2 = txtvalor2.getText();
n1 = Integer.parseInt(num1);
n2 = Integer.parseInt(num2);
total = n1 - n2;
txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_RESTAActionPerformed

    private void DIVISIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVISIONActionPerformed
        // TODO add your handling code here:
        String num1,num2;
int n1,n2,total;
num1 = txtvalor1.getText();
num2 = txtvalor2.getText();
n1 = Integer.parseInt(num1);
n2 = Integer.parseInt(num2);
total = n1 / n2;
txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_DIVISIONActionPerformed

    private void MULTIPLICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTIPLICACIONActionPerformed
        // TODO add your handling code here:
        String num1,num2;
int n1,n2,total;
num1 = txtvalor1.getText();
num2 = txtvalor2.getText();
n1 = Integer.parseInt(num1);
n2 = Integer.parseInt(num2);
total = n1 * n2;
txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_MULTIPLICACIONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem DIVISION;
    private javax.swing.JCheckBoxMenuItem MULTIPLICACION;
    private javax.swing.JCheckBoxMenuItem RESTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu operaciones;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JCheckBoxMenuItem txtsuma;
    private javax.swing.JTextField txtvalor1;
    private javax.swing.JTextField txtvalor2;
    // End of variables declaration//GEN-END:variables
}
