
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Imagen_Producto extends javax.swing.JFrame {
    //producto
//    String producto[] = {"GASEOSA","CEREAL","JABON","CAFE"};
//    String marca[] = {"Pepsi","Kellogs","Dove","Nescafe"};
//    double precio[] = {7.15,11.35,5.55,8.25};
    
    
    String producto[] = {"ACCION","COMEDIA","SUSPENSO","TERROR"};
    String marca[] = {"LUCY","LAS VACACIONES DE MR BEAN","ENOLA HOLMES","SOMNIA (ANTES DE DESPERTAR)"};
    String precio[] = {"25/07/2014","24/03/2007","23/08/2020","15/11/2020"};

        void especificaciones(){
        lbproducto.setText(producto[i]);
        lbmarca.setText(marca[i]);
        lbprecio.setText(String.valueOf(precio[i]));
        }
        int i=0;
    /**
     * Creates new form Imagen_Producto
     */
    public Imagen_Producto() {
        initComponents();
   
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRODUCTO1 = new javax.swing.JButton();
        PRODUCTO2 = new javax.swing.JButton();
        PRODUCTO3 = new javax.swing.JButton();
        PRODUCTO4 = new javax.swing.JButton();
        lbproducto = new javax.swing.JLabel();
        lbmarca = new javax.swing.JLabel();
        lbprecio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dibujo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRODUCTO1.setText("PELICULA 1");
        PRODUCTO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTO1ActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCTO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 43, -1, -1));

        PRODUCTO2.setText("PELICULA 2");
        PRODUCTO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTO2ActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCTO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 94, -1, -1));

        PRODUCTO3.setText("PELICULA 3");
        PRODUCTO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTO3ActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCTO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 151, -1, -1));

        PRODUCTO4.setText("PELICULA 4");
        PRODUCTO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODUCTO4ActionPerformed(evt);
            }
        });
        getContentPane().add(PRODUCTO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 209, -1, -1));

        lbproducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));
        getContentPane().add(lbproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 306, 240, 23));

        lbmarca.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));
        getContentPane().add(lbmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 358, 240, 23));

        lbprecio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));
        getContentPane().add(lbprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 407, 240, 22));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PELICULAS"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dibujo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 102)));
        jPanel1.add(dibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 27, 240, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void PRODUCTO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTO1ActionPerformed
        // PRODUCTO1     

        //Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\cereal.jpg");
       // Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\lata.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
        
        Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\accion.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
        
        ImageIcon figura = new ImageIcon(imagen);
        dibujo.setIcon(figura);
        i=0;
        especificaciones();
    }//GEN-LAST:event_PRODUCTO1ActionPerformed

    private void PRODUCTO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTO2ActionPerformed
        // PRODUCTO2
   // Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\cereal.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
    
    Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\comedia.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
    
    ImageIcon figura = new ImageIcon(imagen);
    dibujo.setIcon(figura);
    i=1;
    especificaciones();
    }//GEN-LAST:event_PRODUCTO2ActionPerformed

    private void PRODUCTO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTO3ActionPerformed
        // PRODUCTO3
   // Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\jabon.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
    
    Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\suspenso.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
    
    ImageIcon figura = new ImageIcon(imagen);
    dibujo.setIcon(figura);
    i=2;
    especificaciones();
    }//GEN-LAST:event_PRODUCTO3ActionPerformed

    private void PRODUCTO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODUCTO4ActionPerformed
        // PRODUCTO4
        //Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\cereal.jpg");
        
        //producto
        //Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\cafe.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
        
        Image imagen = Toolkit.getDefaultToolkit().getImage("C:\\dibujos\\miedo.jpg").getScaledInstance(dibujo.getWidth(), dibujo.getHeight(), 0);
        
        ImageIcon figura = new ImageIcon(imagen);
        dibujo.setIcon(figura);
        i=3;
        especificaciones();
    }//GEN-LAST:event_PRODUCTO4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imagen_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imagen_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PRODUCTO1;
    private javax.swing.JButton PRODUCTO2;
    private javax.swing.JButton PRODUCTO3;
    private javax.swing.JButton PRODUCTO4;
    private javax.swing.JLabel dibujo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbmarca;
    private javax.swing.JLabel lbprecio;
    private javax.swing.JLabel lbproducto;
    // End of variables declaration//GEN-END:variables
}
