
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana
 */
public class Matriz extends javax.swing.JFrame {

    /**
     * Creates new form Matriz
     */
    public Matriz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcolumnas = new javax.swing.JTextField();
        tfilas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmostraramatriz = new javax.swing.JTextArea();
        CALCULARMATRIZ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tmostrarletra = new javax.swing.JTextArea();
        CALCULARLETRA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NUMERO DE COLUMNAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 91, -1, -1));

        jLabel2.setText("NUMERO DE FILAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 130, -1, -1));
        getContentPane().add(tcolumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 88, 167, -1));
        getContentPane().add(tfilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 127, 167, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MATRICES"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tmostraramatriz.setColumns(20);
        tmostraramatriz.setRows(5);
        jScrollPane1.setViewportView(tmostraramatriz);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 260, 140));

        CALCULARMATRIZ.setText("CALCULAR MATRIZ");
        CALCULARMATRIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARMATRIZActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULARMATRIZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 150, 30));

        tmostrarletra.setColumns(20);
        tmostrarletra.setRows(5);
        jScrollPane2.setViewportView(tmostrarletra);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 260, 140));

        CALCULARLETRA.setText("CALCULAR LETRA");
        CALCULARLETRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARLETRAActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULARLETRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CALCULARMATRIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARMATRIZActionPerformed
        // TODO add your handling code here:
        int columnas = Integer.parseInt(tcolumnas.getText());
        int filas = Integer.parseInt(tfilas.getText());
        int matriz[][] = new int[filas][columnas];
        String numero = "";
        String unir = "";
        int f,c;
        for(f=0;f<filas;f++){
        for(c=0;c<columnas;c++){
        numero = JOptionPane.showInputDialog("Matriz " + " Ingresar numero para celda, " + f + ","+ c + ".");
        tmostraramatriz.setText(unir = unir + numero);
        matriz[f][c] = Integer.parseInt(numero);
        }
        tmostraramatriz.setText(unir = unir + "\n");
        }
    }//GEN-LAST:event_CALCULARMATRIZActionPerformed

    private void CALCULARLETRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARLETRAActionPerformed
        // TODO add your handling code here:
        
       int columnas = Integer.parseInt(tcolumnas.getText());
        int filas = Integer.parseInt(tfilas.getText());
        String matriz[][] = new String[filas][columnas];
        String numero = "";
        String unir = "";
        int f,c;
        for(f=0;f<filas;f++){
        for(c=0;c<columnas;c++){
        numero = JOptionPane.showInputDialog("Matriz " +
        " Ingresar letra para celda, " + f + ","+ c + ".");
        tmostrarletra.setText(unir = unir +" " + numero);
        matriz[f][c] = numero;
        }
        tmostrarletra.setText(unir = unir + "\n");
}
    }//GEN-LAST:event_CALCULARLETRAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCULARLETRA;
    private javax.swing.JButton CALCULARMATRIZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tcolumnas;
    private javax.swing.JTextField tfilas;
    private javax.swing.JTextArea tmostraramatriz;
    private javax.swing.JTextArea tmostrarletra;
    // End of variables declaration//GEN-END:variables
}
